[0m20:46:01.819386 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001ABD228D8D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001ABD228DE90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001ABD228DA10>]}


============================== 20:46:01.836663 | ae0d434a-0b45-41d3-a7d7-9bff63a5f6c4 ==============================
[0m20:46:01.836663 [info ] [MainThread]: Running with dbt=1.8.4
[0m20:46:01.836663 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\erikf\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'log_format': 'default', 'invocation_command': 'dbt init my_project', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m20:46:01.959839 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse dict {'dir': WindowsPath('C:/Users/erikf/.dbt')}
[0m20:46:01.960841 [info ] [MainThread]: Creating dbt configuration folder at 
[0m20:46:01.966845 [debug] [MainThread]: Starter project path: c:\Users\erikf\OneDrive\projects\01_GitHub_Projects\04_Project_DBT\.venv\Lib\site-packages\dbt\include\starter_project
[0m20:46:02.011110 [info ] [MainThread]: 
Your new dbt project "my_project" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m20:46:02.011110 [info ] [MainThread]: Setting up your profile.
[0m20:46:02.011110 [error] [MainThread]: Encountered an error:
Runtime Error
  No adapters available. Learn how to install an adapter by going to https://docs.getdbt.com/docs/connect-adapters#install-using-the-cli
[0m20:46:02.019115 [debug] [MainThread]: Command `dbt init` failed at 20:46:02.019115 after 0.24 seconds
[0m20:46:02.019115 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001ABD228E210>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001ABCCE92C90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001ABD2283D90>]}
[0m20:46:02.020424 [debug] [MainThread]: Flushing usage events
[0m20:51:41.203533 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000011BF5466910>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000011BF547ED10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000011BF547EBD0>]}


============================== 20:51:41.203533 | d22e4b18-d18a-4fa1-9b62-7ad19f91a7c9 ==============================
[0m20:51:41.203533 [info ] [MainThread]: Running with dbt=1.8.4
[0m20:51:41.203533 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\erikf\\.dbt', 'version_check': 'True', 'warn_error': 'None', 'log_path': 'logs', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt deps', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m20:51:41.203533 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\erikf\OneDrive\projects\01_GitHub_Projects\04_Project_DBT\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m20:51:41.203533 [debug] [MainThread]: Command `dbt deps` failed at 20:51:41.203533 after 0.06 seconds
[0m20:51:41.203533 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000011BF5489DD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000011BF0012A50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000011BF0012B50>]}
[0m20:51:41.203533 [debug] [MainThread]: Flushing usage events
[0m22:18:38.595670 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022AC5539010>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022AC5539390>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022AC5539D50>]}


============================== 22:18:38.599786 | 0e53a0a9-dfd0-4926-80f3-b98d6e640270 ==============================
[0m22:18:38.599786 [info ] [MainThread]: Running with dbt=1.8.4
[0m22:18:38.600300 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\erikf\\.dbt', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt seed', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m22:18:38.601335 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\erikf\OneDrive\projects\01_GitHub_Projects\04_Project_DBT\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m22:18:38.603396 [debug] [MainThread]: Command `dbt seed` failed at 22:18:38.603396 after 0.07 seconds
[0m22:18:38.603915 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022AC5588090>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022AC558A610>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022AC5583FD0>]}
[0m22:18:38.604942 [debug] [MainThread]: Flushing usage events
[0m22:19:01.349434 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000016776683D90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001677668A310>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001677668A290>]}


============================== 22:19:01.349434 | e13780a1-b114-4ae4-ad60-d4aeb3878244 ==============================
[0m22:19:01.349434 [info ] [MainThread]: Running with dbt=1.8.4
[0m22:19:01.349434 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\erikf\\.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'warn_error': 'None', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m22:19:01.349434 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\erikf\OneDrive\projects\01_GitHub_Projects\04_Project_DBT\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m22:19:01.349434 [debug] [MainThread]: Command `dbt run` failed at 22:19:01.349434 after 0.06 seconds
[0m22:19:01.349434 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001677668A210>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001677668AA10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000016771212AD0>]}
[0m22:19:01.349434 [debug] [MainThread]: Flushing usage events
[0m10:03:53.694342 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000267BED25450>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000267BF18A490>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000267BF18A2D0>]}


============================== 10:03:53.694342 | 565353a0-4b8b-4925-8135-496d60b56485 ==============================
[0m10:03:53.694342 [info ] [MainThread]: Running with dbt=1.8.4
[0m10:03:53.694342 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\erikf\\.dbt', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt run --select raw_sales', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m10:03:53.694342 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\erikf\OneDrive\projects\01_GitHub_Projects\04_Project_DBT\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m10:03:53.710752 [debug] [MainThread]: Command `dbt run` failed at 10:03:53.710752 after 0.06 seconds
[0m10:03:53.710752 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000267B9D12B10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000267BF18A8D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000267BF18A1D0>]}
[0m10:03:53.710752 [debug] [MainThread]: Flushing usage events
